server:
  port: 8087
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: notification
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/