server:
  port: 8761
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: eureka-server
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false